name: minmod

services:
  nginx:
    image: minmod-nginx
    build:
      context: ./containers/nginx/
    volumes:
      - ${CERT_DIR}:/certs/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - minmod
    cap_add:
      - NET_BIND_SERVICE
  api:
    image: minmod
    ports:
      - "8000:8000"
    networks:
      - minmod
    environment:
      - CFG_FILE=/home/criticalmaas/config/config.yml
    volumes:
      - ${CFG_DIR}:/home/criticalmaas/config
    command: fastapi run /home/criticalmaas/kg/minmodkg/api/main.py
  dashboard:
    image: minmod-dashboard
    ports:
      - "8050:8050"
    environment: 
      - API_ENDPOINT=http://api:8000
      - SPARQL_ENDPOINT=http://kg:3030/minmod/sparql
    networks:
      - minmod
    command: "poetry run python app.py"
  editor:
    image: minmod-editor
    ports:
      - 9000:9000
    networks:
      - minmod
    environment:
      - MINMOD_API=http://api:8000
    command: python -m minmod_editor --port 9000

networks:
  minmod:
    name: minmod
    external: true